"""Change telegram_id type from String to BigInteger

Revision ID: 993a85f6efb6
Revises: cbdeecf5dd17
Create Date: 2026-01-19 20:35:33.045632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision = '993a85f6efb6'
down_revision = 'cbdeecf5dd17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE users ALTER COLUMN telegram_id TYPE BIGINT USING telegram_id::bigint")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE users ALTER COLUMN telegram_id TYPE VARCHAR USING telegram_id::varchar")
    # ### end Alembic commands ###