"""Change telegram_id type from String to cart

Revision ID: a0086d605618
Revises: 993a85f6efb6
Create Date: 2026-01-19 21:39:41.112007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision = 'a0086d605618'
down_revision = '993a85f6efb6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###